### ISSUE TITLE
Fix deployment_state on NB versions with pull support and version up to 2.0.0 pre-release.

### ISSUE THREAD

**Issue by schaubl** [nuvla/job-engine#202]
Actions `deployment_state_10` and `deployment_state_60` have been renamed to `deployment_state` in e727d068d6753bf03a7d2f45243a33364edab8dc and the distributor now distribute only `deployment_state` actions.
It is ok for the job-engine on Nuvla.io which has been updated but the NuvlaBoxes still run older versions where the `deployment_state` action doesn't exist.

**Comment by cjdcordeiro** [comment]
Possible remediations:
 - keep the old deployment_state_Xs jobs in the server, so that existing NBs version can still pick them up
 - create a new NB component to replace the job-lite, that instead of forking a specific version of the job-engine, it simply synchronizes with the latest version of the job-engine upstream, pulling its latest version whenever necessary
 - let the NB agent create its own deployment_state jobs: https://github.com/nuvla/job-engine/issues/160
